service: goservice
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
#  secure: always

skip_files:
- ^(.*~)$
- ^(.gitignore)$
- ^(.git)$
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?\.cmd$
- ^(.*/)?\.md$