# [START app_yaml]
service: default
runtime: aspnetcore
api_version: '1.0'
env: flexible
threadsafe: true
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 20
  cpu_utilization:
    target_utilization: 0.5